version: '3'

services:
    
    database:
        container_name: cqrs-container-mssql
        image: mcr.microsoft.com/mssql/server
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: P@55w0rd
            ACCEPT_EULA: Y
        networks:
          - cqrs-net

    rabbitmq:
        container_name: cqrs-container-rabbitmq
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        environment:
          - RABBITMQ_DEFAULT_USER=rabbitmquser
          - RABBITMQ_DEFAULT_PASS=r4bb1t
        networks:
          - cqrs-net

    elasticsearch:
        container_name: cqrs-container-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        environment:
          - xpack.security.enabled=false
          - discovery.type=single-node
        networks:
          - cqrs-net
        ports:
          - 9200:9200
          
    kibana:
        container_name: cqrs-container-kibana
        image: docker.elastic.co/kibana/kibana:7.11.0
        environment:
            - ELASTICSEARCH_HOSTS=http://cqrs-container-elasticsearch:9200
        networks:
            - cqrs-net
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601

networks:
    cqrs-net:
        driver: bridge
